

[stages]
stage1 = ["fetch_song_info"]
stage2 = ["infocopy"]
stage3 = [
    "albumui",
    "trackcounter"
]
stage4 = [
    "tagui",
    "download"
]
stage5 = [
    "tag_files",
    "albumcover"
]
stage6 = ["rename"]


# Infocopy copies values from the yt-dlp json to the songinfo
[stages.infocopy]
title = "track"
album = "album"
artist = "artist"

[stages.rename]
template = "%(artist) - %(title).%(ext)"
